
HandyNotes_ShadowlandsDB = {
	["profileKeys"] = {
		["Luká - Frostmane"] = "Default",
		["Felbladë - Tarren Mill"] = "Default",
		["Fëlblade - Tarren Mill"] = "Default",
		["Öak - Frostmane"] = "Default",
		["Dmthyltryp - Tarren Mill"] = "Default",
		["Yaöb - Tarren Mill"] = "Default",
		["Cëll - Tarren Mill"] = "Default",
		["Swervë - Tarren Mill"] = "Default",
		["Väel - Tarren Mill"] = "Default",
		["Säuce - Tarren Mill"] = "Default",
		["Blighthöund - Tarren Mill"] = "Default",
		["Tidës - Frostmane"] = "Default",
		["Venedictia - Frostmane"] = "Default",
		["Tribës - Tarren Mill"] = "Default",
		["Fabr - Frostmane"] = "Default",
		["Løtüs - Tarren Mill"] = "Default",
		["Ööunusedöö - Tarren Mill"] = "Default",
		["Notrageqtz - Tarren Mill"] = "Default",
		["Nothoit - Tarren Mill"] = "Default",
		["Bäsics - Tarren Mill"] = "Default",
		["Petrølbømb - Tarren Mill"] = "Default",
		["Fëlstriker - Tarren Mill"] = "Default",
		["Notkeuch - Tarren Mill"] = "Default",
		["Gorë - Tarren Mill"] = "Default",
		["Klöse - Silvermoon"] = "Default",
		["Nervë - Tarren Mill"] = "Default",
		["Nervë - Silvermoon"] = "Default",
		["Moolerlight - Tarren Mill"] = "Default",
		["Klöse - Tarren Mill"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
		},
	},
}
