
PawnCommon = {
	["ShowUpgradesOnTooltips"] = true,
	["AlignNumbersRight"] = false,
	["ShowBagUpgradeAdvisor"] = true,
	["ShowItemID"] = false,
	["ShowRelicUpgrades"] = false,
	["ShowValuesForUpgradesOnly"] = true,
	["ShowItemLevelUpgrades"] = true,
	["ShownGettingStarted"] = true,
	["Debug"] = false,
	["ColorTooltipBorder"] = true,
	["ShowTooltipIcons"] = true,
	["Scales"] = {
		["\"MrRobot\":HUNTER3"] = {
			["IconTexturePath"] = 461113,
			["PerCharacterOptions"] = {
				["Yaöb-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Survival",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "7e9d54",
		},
		["\"MrRobot\":WARLOCK1"] = {
			["IconTexturePath"] = 136145,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8687ed",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Affliction",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "6465b1",
		},
		["\"MrRobot\":SHAMAN1"] = {
			["IconTexturePath"] = 136048,
			["PerCharacterOptions"] = {
				["Notkeuch-Tarren Mill"] = {
					["Visible"] = true,
				},
				["Cëll-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Elemental",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "0053a5",
		},
		["\"MrRobot\":PRIEST1"] = {
			["IconTexturePath"] = 135940,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fefefe",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Discipline",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bebebe",
		},
		["noxxic_vengeance_demon_hunter"] = {
			["PerCharacterOptions"] = {
				["Fëlblade-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Values"] = {
				["Agility"] = 6.15,
				["HasteRating"] = 6.05,
				["MasteryRating"] = 5.05,
				["CritRating"] = 4.59,
				["Versatility"] = 5.65,
			},
			["UpgradesFollowSpecialization"] = true,
		},
		["\"MrRobot\":PRIEST3"] = {
			["IconTexturePath"] = 136207,
			["PerCharacterOptions"] = {
				["Dmthyltryp-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fefefe",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Shadow",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bebebe",
		},
		["\"MrRobot\":MAGE3"] = {
			["IconTexturePath"] = 135846,
			["PerCharacterOptions"] = {
				["Petrølbømb-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3ec6ea",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Frost",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "2e94af",
		},
		["\"MrRobot\":MAGE2"] = {
			["IconTexturePath"] = 135810,
			["PerCharacterOptions"] = {
			},
			["Color"] = "3ec6ea",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Fire",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "2e94af",
		},
		["\"MrRobot\":WARLOCK3"] = {
			["IconTexturePath"] = 136186,
			["PerCharacterOptions"] = {
				["Blighthöund-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8687ed",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Destruction",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "6465b1",
		},
		["noxxic-legacy-death-knight-blood"] = {
			["Values"] = {
				["Str"] = 6.19,
				["Leech"] = -0.06,
				["CritRating"] = 4.29,
				["Bonusarmor"] = -0.04,
				["HasteRating"] = 3,
				["MasteryRating"] = 3.83,
				["Stamina"] = -0.05,
				["Armor"] = -0.05,
				["Versatility"] = 4.23,
			},
			["PerCharacterOptions"] = {
				["Klöse-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["UpgradesFollowSpecialization"] = true,
		},
		["\"MrRobot\":ROGUE2"] = {
			["IconTexturePath"] = 236286,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Outlaw",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "beb64d",
		},
		["\"MrRobot\":MONK1"] = {
			["IconTexturePath"] = 608951,
			["PerCharacterOptions"] = {
				["Løtüs-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Brewmaster",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "00be71",
		},
		["\"MrRobot\":DEMONHUNTER1"] = {
			["IconTexturePath"] = 1247264,
			["PerCharacterOptions"] = {
				["Fëlblade-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a22fc8",
			["ClassID"] = 12,
			["LocalizedName"] = "Demon Hunter: Havoc",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "792396",
		},
		["\"MrRobot\":DRUID4"] = {
			["IconTexturePath"] = 136041,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Restoration",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 4,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":PALADIN1"] = {
			["IconTexturePath"] = 135920,
			["PerCharacterOptions"] = {
				["Moolerlight-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Holy",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "b6688a",
		},
		["noxxic_protection_paladin"] = {
			["IconTexturePath"] = 236264,
			["Values"] = {
				["IsOffHand"] = -1000000,
				["IsFist"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 4.85,
				["IsBow"] = -1000000,
				["Strength"] = 7.57,
				["IsWand"] = -1000000,
				["IsStaff"] = -1000000,
				["IsDagger"] = -1000000,
				["HasteRating"] = 6.07,
				["MasteryRating"] = 5.26,
				["IsCrossbow"] = -1000000,
				["Versatility"] = 5.26,
				["IsThrown"] = -1000000,
				["IsGun"] = -1000000,
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["Role"] = "TANK",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 2,
			["PerCharacterOptions"] = {
				["Moolerlight-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
		},
		["noxxic_holy_paladin"] = {
			["IconTexturePath"] = 135920,
			["Values"] = {
				["Intellect"] = 6.58,
				["IsFist"] = -1000000,
				["IsWand"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 6.18,
				["IsStaff"] = -1000000,
				["IsBow"] = -1000000,
				["IsOffHand"] = -1000000,
				["IsDagger"] = -1000000,
				["HasteRating"] = 6.56,
				["MasteryRating"] = 6.42,
				["Versatility"] = 6.22,
				["IsCrossbow"] = -1000000,
				["IsThrown"] = -1000000,
				["IsGun"] = -1000000,
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["Role"] = "HEALER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["PerCharacterOptions"] = {
				["Moolerlight-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
		},
		["noxxic-legacy-warrior-fury"] = {
			["IconTexturePath"] = 132347,
			["Values"] = {
				["Str"] = 6.11,
				["IsFrill"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 4.88,
				["IsBow"] = -1000000,
				["IsWand"] = -1000000,
				["HasteRating"] = 3.12,
				["MasteryRating"] = 5.45,
				["Versatility"] = 4.84,
				["IsCrossbow"] = -1000000,
				["IsGun"] = -1000000,
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 2,
			["PerCharacterOptions"] = {
				["Nervë-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":ROGUE3"] = {
			["IconTexturePath"] = 132320,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Subtlety",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "beb64d",
		},
		["JP Survival"] = {
			["IconTexturePath"] = 461113,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFrill"] = -1000000,
				["Is2HMace"] = -1000000,
				["IsMace"] = -1000000,
				["CritRating"] = 3.77,
				["IsPlate"] = -1000000,
				["Agility"] = 6.56,
				["HasteRating"] = 2.96,
				["MasteryRating"] = 1.9,
				["Versatility"] = 3.48,
				["IsShield"] = -1000000,
				["IsWarglaive"] = -1000000,
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 3,
			["PerCharacterOptions"] = {
				["Yaöb-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":WARRIOR3"] = {
			["IconTexturePath"] = 132341,
			["PerCharacterOptions"] = {
				["Nervë-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Protection",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "937351",
		},
		["\"MrRobot\":PRIEST2"] = {
			["IconTexturePath"] = 237542,
			["PerCharacterOptions"] = {
				["Notrageqtz-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fefefe",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Holy",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bebebe",
		},
		["\"MrRobot\":PALADIN3"] = {
			["IconTexturePath"] = 135873,
			["PerCharacterOptions"] = {
				["Moolerlight-Tarren Mill"] = {
					["Visible"] = true,
				},
				["Nothoit-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Retribution",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "b6688a",
		},
		["JP Brewmaster"] = {
			["IconTexturePath"] = 608951,
			["Values"] = {
				["IsWand"] = -1000000,
				["Is2HMace"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 6.06,
				["Agility"] = 3.9,
				["HasteRating"] = 4.3,
				["MasteryRating"] = 4.56,
				["IsCrossbow"] = -1000000,
				["IsThrown"] = -1000000,
				["IsFrill"] = -1000000,
				["Is2HAxe"] = -1000000,
				["IsBow"] = -1000000,
				["IsMail"] = -1000000,
				["IsPlate"] = -1000000,
				["IsDagger"] = -1000000,
				["IsOffHand"] = -1000000,
				["Versatility"] = 6.11,
				["Is2HSword"] = -1000000,
				["IsShield"] = -1000000,
				["IsGun"] = -1000000,
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["Role"] = "TANK",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["PerCharacterOptions"] = {
				["Løtüs-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
		},
		["JP Enhancement"] = {
			["IconTexturePath"] = 237581,
			["PerCharacterOptions"] = {
				["Notkeuch-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 2,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 3.95,
				["Agility"] = 7.63,
				["HasteRating"] = 4.47,
				["MasteryRating"] = 4.32,
				["IsCrossbow"] = -1000000,
				["IsPolearm"] = -1000000,
				["IsGun"] = -1000000,
				["IsSword"] = -1000000,
				["IsFrill"] = -1000000,
				["IsThrown"] = -1000000,
				["IsBow"] = -1000000,
				["IsPlate"] = -1000000,
				["Is2HSword"] = -1000000,
				["IsShield"] = -1000000,
				["Versatility"] = 3.85,
			},
		},
		["\"MrRobot\":DEMONHUNTER2"] = {
			["IconTexturePath"] = 1247265,
			["PerCharacterOptions"] = {
				["Felbladë-Tarren Mill"] = {
					["Visible"] = true,
				},
				["Fëlblade-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a22fc8",
			["ClassID"] = 12,
			["LocalizedName"] = "Demon Hunter: Vengeance",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "792396",
		},
		["\"MrRobot\":WARRIOR1"] = {
			["IconTexturePath"] = 132355,
			["PerCharacterOptions"] = {
				["Nervë-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Arms",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "937351",
		},
		["\"MrRobot\":WARLOCK2"] = {
			["IconTexturePath"] = 136172,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8687ed",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Demonology",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "6465b1",
		},
		["noxxic_retribution_paladin"] = {
			["IconTexturePath"] = 135873,
			["Values"] = {
				["IsOffHand"] = -1000000,
				["IsFist"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 3.66,
				["IsBow"] = -1000000,
				["Strength"] = 5.9,
				["IsWand"] = -1000000,
				["IsStaff"] = -1000000,
				["IsDagger"] = -1000000,
				["HasteRating"] = 3.49,
				["MasteryRating"] = 3.72,
				["IsCrossbow"] = -1000000,
				["Versatility"] = 3.46,
				["IsThrown"] = -1000000,
				["IsGun"] = -1000000,
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 3,
			["PerCharacterOptions"] = {
				["Moolerlight-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":SHAMAN3"] = {
			["IconTexturePath"] = 136052,
			["PerCharacterOptions"] = {
				["Notkeuch-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Restoration",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "0053a5",
		},
		["\"MrRobot\":DRUID2"] = {
			["IconTexturePath"] = 132115,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Feral",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":DEATHKNIGHT1"] = {
			["IconTexturePath"] = 135770,
			["PerCharacterOptions"] = {
				["Klöse-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Blood",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":HUNTER1"] = {
			["IconTexturePath"] = 461112,
			["PerCharacterOptions"] = {
				["Yaöb-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Beast Mastery",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "7e9d54",
		},
		["\"MrRobot\":DEATHKNIGHT3"] = {
			["IconTexturePath"] = 135775,
			["PerCharacterOptions"] = {
				["Klöse-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Unholy",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":HUNTER2"] = {
			["IconTexturePath"] = 236179,
			["PerCharacterOptions"] = {
				["Yaöb-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Marksmanship",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "7e9d54",
		},
		["\"MrRobot\":WARRIOR2"] = {
			["IconTexturePath"] = 132347,
			["PerCharacterOptions"] = {
				["Nervë-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Fury",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "937351",
		},
		["\"MrRobot\":MONK2"] = {
			["IconTexturePath"] = 608952,
			["PerCharacterOptions"] = {
				["Løtüs-Tarren Mill"] = {
					["Visible"] = true,
				},
				["Säuce-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Mistweaver",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "00be71",
		},
		["\"MrRobot\":DEATHKNIGHT2"] = {
			["IconTexturePath"] = 135773,
			["PerCharacterOptions"] = {
				["Klöse-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Frost",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":PALADIN2"] = {
			["IconTexturePath"] = 236264,
			["PerCharacterOptions"] = {
				["Moolerlight-Tarren Mill"] = {
					["Visible"] = true,
				},
				["Bäsics-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Protection",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "b6688a",
		},
		["\"MrRobot\":MAGE1"] = {
			["IconTexturePath"] = 135932,
			["PerCharacterOptions"] = {
			},
			["Color"] = "3ec6ea",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Arcane",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "2e94af",
		},
		["\"MrRobot\":ROGUE1"] = {
			["IconTexturePath"] = 236270,
			["PerCharacterOptions"] = {
				["Fëlstriker-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Assassination",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "beb64d",
		},
		["\"MrRobot\":DRUID3"] = {
			["IconTexturePath"] = 132276,
			["PerCharacterOptions"] = {
				["Gorë-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Guardian",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":DRUID1"] = {
			["IconTexturePath"] = 136096,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Balance",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":SHAMAN2"] = {
			["IconTexturePath"] = 237581,
			["PerCharacterOptions"] = {
				["Notkeuch-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Enhancement",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "0053a5",
		},
		["\"MrRobot\":MONK3"] = {
			["IconTexturePath"] = 608953,
			["PerCharacterOptions"] = {
				["Løtüs-Tarren Mill"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Windwalker",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "00be71",
		},
	},
	["ShowSocketingAdvisor"] = true,
	["ShowSpecIcons"] = true,
	["IgnoreGemsWhileLeveling"] = true,
	["ButtonPosition"] = 2,
	["ShowLootUpgradeAdvisor"] = true,
	["ShowQuestUpgradeAdvisor"] = true,
	["LastVersion"] = 2.0702,
	["Digits"] = 1,
}
